### ISSUE TITLE
Do we want to get rid of the blue focus rings?

### ISSUE THREAD

**Issue by critocrito** [bitspossessed/culturestake#154]
At least on Chrome we have those blue focus rings around buttons and form elements. They are important for keyboard navigation but I find them horrific to look at.

![Screen Shot 2021-03-10 at 10 06 39](https://user-images.githubusercontent.com/29301569/110604394-efdd0080-817f-11eb-916e-b357613f870c.png)

What I usually do is to disable them and only once a user tabs I turn them on. This would look something like that:

```css
/* In the CSS file we disable the focus rings */
body:not(.user-is-tabbing) button:focus,
body:not(.user-is-tabbing) input:focus,
body:not(.user-is-tabbing) select:focus,
body:not(.user-is-tabbing) textarea:focus {
  outline: none;
}
```

```js
// In the React root we look out for the first tab event.
const App = () => {
  const [firstTabHandled, setFirstTabHandled] = useState(false);

  // enable form focus rings when tabbing
  useEffect(() => {
    if (firstTabHandled) return;

    const handleFirstTab = (ev: KeyboardEvent) => {
      // the "I am a keyboard user" key
      if (ev.key === "Tab") {
        document.body.classList.add("user-is-tabbing");
        window.removeEventListener("keydown", handleFirstTab);
      }
    };

    window.addEventListener("keydown", handleFirstTab);
    setFirstTabHandled(true);

    return () => window.removeEventListener("keydown", handleFirstTab);
  }, [firstTabHandled]);

  return <div />;
}
```

@aeluteia, @ana0 how do you feel about that? Shall we implement that?
